### ISSUE TITLE
Provide an artifact in the maven central repository

### ISSUE THREAD

**Issue by dharezlak** [pesse/gwt-jsinterop-threejs#1]
It would be great to have a jar available in the maven central repository.

**Comment by pesse** [comment]
Hi dharezlak,
unfortunatley I'm not sure how much I can push the project at the moment due to job situation (this is a leisure time project). It's far from being completed, there is still a huge amount of work to do and I don't want to release a not even half-finished version to maven central.
You are very welcome to contribute, though :)

Best regards,
Pesse

**Comment by dharezlak** [comment]
Thanks for the reply. Unfortunately, my time resources are depleted at the moment to contribute :(
